name: Bless
version: 1.0.0
main: TPE\Bless\Bless
api: 3.0.0
author: TPE

commands:
  bless:
    description: "Bless yourself!"
    permission: bless.command
    aliases: ["cleanse"]
    
permissions:
  bless.command:
    default: op
