# Message sent to players when they bless themselves.
blessed-self-message: "§e***§lBLESSED§r§e***"

# Message sent to player if they lack permissions to bless themselves.
no-perms-self-bless: "§cYou do not have permission to bless yourself!"

# Cooldown in seconds for the /bless command
bless-cooldown-time: 300

# Message sent to player if /bless is on cooldown, use %REMAINING% for the time remaining.
cooldown-message: "§cYou can not bless yourself for another %REMAINING% seconds!"
